{
  "controlTypeValues": {
    "TcHmi.Controls.Beckhoff.TcHmiButton": {
      "attributes": {
        "BackgroundColor": {
          "color": "rgba(248, 198, 42, 1)"
        },
        "BorderColor": {
          "color": "rgba(0, 0, 0, 1)"
        },
        "TextColor": {
          "color": "rgba(0, 0, 0, 1)"
        },
        "BorderRadius": {
          "topLeft": 5.0,
          "topRight": 5.0,
          "bottomLeft": 5.0,
          "bottomRight": 5.0,
          "topLeftUnit": "px",
          "topRightUnit": "px",
          "bottomLeftUnit": "px",
          "bottomRightUnit": "px"
        },
        "BorderWidth": {
          "left": 2,
          "right": 2,
          "top": 2,
          "bottom": 2,
          "leftUnit": "px",
          "rightUnit": "px",
          "topUnit": "px",
          "bottomUnit": "px"
        },
        "BorderStyle": {
          "left": "Solid",
          "right": "Solid",
          "top": "Solid",
          "bottom": "Solid"
        }
      },
      "themedResources": {}
    }
  },
  "controlClassValues": {},
  "$schema": "./../../../Packages/Beckhoff.TwinCAT.HMI.Framework.12.752.0/runtimes/native1.12-tchmi/Schema/ThemeDescription.Schema.json"
}