<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Furnace" Id="{33587298-d4a9-409c-8fb0-adcf99367898}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Furnace
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Furnace">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>