<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Gantry" Id="{b7979926-7c32-4a40-91b9-f80b9f875b86}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Gantry IMPLEMENTS I_Gantry
VAR_INPUT
	bExecuteHeatSetCycle 	: BOOL;
	bGoHome 				: BOOL;		// nStateVariable 0
	bGoPreHeatSet 			: BOOL;		// nStateVariable 1
	bGoHeatSet 				: BOOL;		// nStateVariable 2
	bGoPreQuench 			: BOOL;		// nStateVariable 3
	bGoQuench 				: BOOL;		// nStateVariable 4
	bStayIdle				: BOOL; 	// nStateVariable 5
END_VAR
VAR_OUTPUT
	bAtHome 				: BOOL;
	bAtPreHeatSet 			: BOOL;
	bAtHeatSet 				: BOOL;
	bAtPreQuench 			: BOOL;
	bAtQuench 				: BOOL;
	bBusy					: BOOL;
	bHeatSetCycleFinished	: BOOL;
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <Method Name="M_GetPosition" Id="{6c46e1df-189d-43c8-9e2b-6900e84dd619}">
      <Declaration><![CDATA[METHOD M_GetPosition : STRING
VAR_INPUT
END_VAR
VAR_OUTPUT
	sCurrentPosition : STRING(20);
END_VAR]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_GoHeatSet" Id="{8b9c9a03-5ab0-4ab0-9b0e-7f7f2056d297}">
      <Declaration><![CDATA[METHOD M_GoHeatSet : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_GoHome" Id="{05dbe8a7-0b0b-420d-9498-f075349f58d9}">
      <Declaration><![CDATA[METHOD M_GoHome : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_GoPreHeatSet" Id="{ded55a42-b141-4de7-8bbe-c2cac1261a54}">
      <Declaration><![CDATA[METHOD M_GoPreHeatSet : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <Method Name="M_GoQuench" Id="{51ae5595-6f83-4590-9a50-47aeaabe3589}">
      <Declaration><![CDATA[METHOD M_GoQuench : BOOL
VAR_INPUT
END_VAR
]]></Declaration>
      <Implementation>
        <ST><![CDATA[]]></ST>
      </Implementation>
    </Method>
    <LineIds Name="FB_Gantry">
      <LineId Id="71" Count="0" />
    </LineIds>
    <LineIds Name="FB_Gantry.M_GetPosition">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Gantry.M_GoHeatSet">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Gantry.M_GoHome">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Gantry.M_GoPreHeatSet">
      <LineId Id="5" Count="0" />
    </LineIds>
    <LineIds Name="FB_Gantry.M_GoQuench">
      <LineId Id="5" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>