<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.11">
  <POU Name="FB_Lights" Id="{e9373f71-6e7d-4a04-865a-64e7b49a0a42}" SpecialFunc="None">
    <Declaration><![CDATA[FUNCTION_BLOCK FB_Lights
VAR_INPUT
END_VAR
VAR_OUTPUT
END_VAR
VAR
END_VAR
]]></Declaration>
    <Implementation>
      <ST><![CDATA[]]></ST>
    </Implementation>
    <LineIds Name="FB_Lights">
      <LineId Id="9" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>