<?xml version="1.0" encoding="utf-8"?>
<TcPlcObject Version="1.1.0.1" ProductVersion="3.1.4024.10">
  <POU Name="MAIN" Id="{efa7bdf7-c0cf-482e-b1df-3f80349c525c}" SpecialFunc="None">
    <Declaration><![CDATA[PROGRAM MAIN
VAR
	
// general use variables
sMachineState		: STRING(10);

tTotalCycleTime 	: TIME;
tHeatSetDuration	: TIME;
tQuenchDuration		: TIME;

fbFurnace 		: FB_Furnace;
fbGantry 		: FB_Gantry;
fbQuenchTank 	: FB_QuenchTank;


// salt furnace variables


// quench tank variables


END_VAR


]]></Declaration>
    <Implementation>
      <ST><![CDATA[IF sMachineState = 'Idle' THEN
	
ELSIF sMachineState = 'Navigating to Start Position' THEN
	
ELSIF sMachineState = 'Waiting for Start' THEN
	
ELSIF sMachineState = 'Heat Soaking' THEN
	
ELSIF sMachineState = 'Navigating to Quench' THEN
	
ELSIF sMachineState = 'Quenching' THEN
	
ELSIF sMachineState = 'Navigating Home' THEN
	
END_IF]]></ST>
    </Implementation>
    <LineIds Name="MAIN">
      <LineId Id="94" Count="0" />
      <LineId Id="97" Count="0" />
      <LineId Id="99" Count="0" />
      <LineId Id="133" Count="1" />
      <LineId Id="102" Count="0" />
      <LineId Id="135" Count="1" />
      <LineId Id="138" Count="1" />
      <LineId Id="137" Count="0" />
      <LineId Id="142" Count="0" />
      <LineId Id="141" Count="0" />
      <LineId Id="140" Count="0" />
      <LineId Id="98" Count="0" />
    </LineIds>
  </POU>
</TcPlcObject>